### ISSUE TITLE
Option to show the output of a (bash) command?

### ISSUE THREAD

**Issue by daroczig** [stuartlangridge/gnome-shell-clock-override#1]
Hi, thanks a lot for this useful extension. I'd like to show two time zones that I'm currently doing with [argos](https://github.com/p-e-w/argos) in a separate widget using the `date` command, but would love to rather replace the default clock indicator. Any chance to do this with this extension?

**Comment by stuartlangridge** [comment]
This is possible but it would complicate the UI rather a lot, and shelling out to a bash command once a second is a bit inefficient. I won't close this, because I can see that there may be value in it, but I'm not planning to work on it; if someone proposes how the UI would work in a way that isn't confusing then I'd be happy to say whether I like that and take a pull request to implement the UI that's been agreed.

**Comment by da2x** [comment]
I’ll close this, however. This could severely affect shell performance. We can’t update the clock asynchronously, so pulling this off without killing performance would be quite complex. This functionality is also out of scope for an extension that is intended for override the time and date format.
